---
title: "Chromebook Data Science Plus (CBDS+)"
output: html_document
---

_Chromebook Data Science Plus (CBDS+)_ is a supplementary program in addition to CBDS and constitutes tutoring and job placement programs in the field of data science for historically underserved populations. We are currently running the program in Baltimore in collaboration with local non-profits. The goal of CBDS+ is to provide additional support to learners from underprivileged communities. CBDS+ focuses on training economically disadvantaged students with minimal academic backgrounds to a level that they could take these jobs.


Through massive online open courses created at Johns Hopkins Biostatistics, we have already taught more than 4 million people data science online through Coursera. Our research has shown that our \$1,000 Coursera program has a significant causal benefit on the economic prospects of students both in terms of increased salary and job mobility. But the more interesting thing is that a small subset of students made less than \$20,000 per year before the program and ended up making more than $40,000 after the program. This represents moving from below poverty levels to the middle class!

The tutoring program provides additional funding and a cheap laptop (< $450)  so they can complete the program. The students are identified with non-profit partners who provide GED math and science training. The students receive three hours a week of in-person tutoring and access to an online chat channel for additional support. They also receive help in placement in data science jobs. We are looking for partners to help us support this program. 
