---
title: "Frequently Asked Questions"
output: html_document
---

-----

[What is the Chromebook Data Science (CBDS) program?](#what-is-the-chromebook-data-science-cbds-program)  
[What is the Chromebook Data Science Plus (CBDS+) program?](#what-is-the-chromebook-data-science-plus-cbds-program) [What is data science?](#what-is-data-science)  
[What do I need to start CBDS?](#what-do-i-need-to-start-cbds)  
[Can I join CBDS+?](#can-i-join-cbds)   
[What is the cost of CBDS?](#what-is-the-cost-of-cbds)  
[How long will it take to complete CBDS?](#how-long-will-it-take-to-complete-cbds)  
[Do I need a college degree to join?](#do-i-need-a-college-degree-to-join)   
[Do I need to know how to code?](#do-i-need-to-know-how-to-code)  
[How do I join?](#how-do-i-join)  
[What skills will I learn?](#what-skills-will-i-learn)  
[What do I get upon completion of CBDS?](#what-do-i-get-upon-completion-of-cbds)   
[How can my non-profit organization get involved?](#how-can-my-non-profit-organization-get-involved)


-----

## What is the Chromebook Data Science (CBDS) program?

Chromebook Data Science (CBDS) is an online educational program to help anyone who can read, write, and use a computer to move into data science. It is offered by faculty members in the Johns Hopkins Department of Biostatistics, Johns Hopkins Bloomberg School of Public Health.


## What is the Chromebook Data Science Plus (CBDS+) program?

Chromebook Data Science Plus (CBDS+) is a supplamentary program in addition to CBDS and constitutes tutoring and job placement program in the field of data science for historically underserved populations. We are currently running the program in Baltimore in collaboration with local non-profits. The goal of CBDS+ is to provide additional support to learners from underprivileged communities. CBDS+ focuses on training economically disadvantaged students with minimal academic backgrounds to a level that they could take these jobs. 


## What is data science?

Simply, data science is the process of *using data to answer interesting questions*. More specifically, throughout the course, we define data science to be:

> the process of formulating a quantitative question that can be answered with data, collecting and cleaning the data, analyzing the data, and communicating the answer to the question to a relevant audience.

See [Jeff's post about Data Science](https://simplystatistics.org/2015/03/17/data-science-done-well-looks-easy-and-that-is-a-big-problem-for-data-scientists/) for more information.



## What do I need to start CBDS?

The classes only require access to a computer and an internet connection. If you don't access to these, both are often available at a local library. And, you will have to want to learn.  Most of the courses are self-guided and require you to push yourself to complete them. 

## Can I join CBDS+?

Unfortunately, CBDS+ is only available in Baltimore, MD and there is no open enrollment for the program. We are hoping to expand the program nationally. However, CBDS is available for anyone interested in learning data science at no cost.


## What is the cost of CBDS? 

You can pay what you want to take the courses and get the certificates (including nothing at all!). 



## How long will it take to complete CBDS?

The program is made up of 12 courses. The advantage of the program is that you can take the classes at your pace and order. The suggested order of the classes is provided [here](./cbds.html).



## Do I need a college degree to join?

No!  The only requirements that you need are a standard high school background in mathematics (such as algebra) and the ability to use a computer.  Our classes require an internet connection, which is usually available at a local library if you do not have one at home.



## Do I need to know how to code?

No. These courses will teach you the skills you need to know to be an effective data scientist.  



## How do I join?

All classes are launched on the Leanpub platform. You can find the courses [here]().



## What skills will I learn?

The coursework will start with the basics of using Google's web browser (Google Chrome) and Google Products (such as Google Docs and Google Sheets). The coursework will then move to learning how to program in the statistical language R and using software such as Markdown, RStudio, and GitHub. Throughout this program you will learn how to work with data, the basics of data analysis and machine learning, and how to visualize data. You will learn how to carry out projects from start to finish and design your own website. We also have courses on soft skills such as communication skills and how to get a job in data science.



## What do I get upon completion of CBDS?

Upon completion of each course in the program, you will get a certificate for each Johns Hopkins online class from Leanpub.

## How can my non-profit organization get involved?

If you are a non-profit located in the United States and you are interested in collaborating with us in teaching data science to disadvantaged communities in your area, contact us [here](./contact.html).