---
title: "For Employers"
---

```{r, echo=FALSE}
library(htmltools)
h3("Are you looking for highly trained data scientists? Are you having trouble identifying, attracting, evaluating, and hiring top talent? If you are interested in becoming a hiring partner and hiring remote data workers from our Chromebook Data Science program please complete the survey below.")
```

------

### __Survey__

```{r, echo=FALSE}
HTML('<div class="typeform-widget" data-url="https://jhudatasci.typeform.com/to/nKnM7Q" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;" > powered by <a href="https://www.typeform.com//?utm_campaign=nKnM7Q&amp;utm_source=typeform.com-10412336-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-poweredbytypeform&amp;utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>')
```

